# laiqverse_art.py
print("🎨 LAiQVerse Art Project")
print("=" * 30)
print("✨ Welcome to my art gallery! ✨")
print()
print("    *")
print("   ***")
print("  *****")
print(" *******")
print("*********")
print("    *")
print("    *")
print()
print("Made by LaiqQureshi")
